services:
  - type: web
    name: ember-chat
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: GROQ_API_KEY
        value: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
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      
